[package]
name = "N_BODY_PARALLEL"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "=1.4"
getrandom = "0.2.12"
js = "0.5.7"
rayon = "1.8.1"
